echo0:
	g++ echo0.cpp -o echo0 -fno-stack-protector -z execstack
echo1:
	g++ echo1.cpp -o echo1 -fno-stack-protector -z execstack
echo1_canary:
	g++ echo1.cpp -o echo1_canary -z execstack
echo2:
	g++ echo2.cpp -o echo2 -fno-stack-protector -z execstack


