echo0:
	g++ echo0.cpp -o echo0 -fno-stack-protector -z execstack
echo1:
	g++ echo1.cpp -o echo1 -fno-stack-protector -z execstack
echo1_canary:
	g++ echo1.cpp -o echo1_canary -z execstack
echo2:
	g++ echo2.cpp -o echo2 -fno-stack-protector -z execstack
echo3:
	g++ echo3.cpp -o echo3 -fno-stack-protector -z execstack
echo4:
	g++ echo4.cpp -o echo4 -fno-stack-protector -z execstack
echo5:
	g++ echo5.cpp -o echo5 -fno-stack-protector -z execstack


